coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 5%
        # Don't fail on patch coverage for dependency updates
        only_pulls: true
        informational: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

# Ignore generated files and test files from coverage
ignore:
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/test/**"
  - "**/tests/**"
  - "scripts/**"
  - "vscode-extension/**"
