/**
 * PNG Export for Specter
 *
 * Generates shareable PNG images from terminal output.
 * Parses ANSI colors and renders beautifully styled images
 * optimized for social media sharing.
 */

import * as fs from 'node:fs'
import * as path from 'node:path'
import { type CanvasRenderingContext2D, createCanvas } from 'canvas'
import { type SimpleGit, simpleGit } from 'simple-git'
import {
  calculateContentArea,
  drawQrCode,
  drawTerminalBox,
  drawTerminalHeader,
  drawTextContent,
  drawWatermark,
  setupCanvas,
} from './export-png-helpers.js'
import { getContentConfig, type ParsedLine, parseAnsiCodes } from './export-png-parsing.js'

export interface PngExportOptions {
  width?: number // Default 1200 (Twitter-optimized)
  height?: number // Auto-calculated if not provided
  theme?: 'dark' | 'light' // Default dark
  watermark?: boolean // Default true - "Generated by Specter"
  padding?: number // Default 40
  lineHeight?: number // Default 1.4
  fontSize?: number // Default 16
  qrUrl?: string // URL to encode as QR code (bottom-right corner)
  socialFormat?: boolean // Force 1200x630 (Twitter/LinkedIn card) dimensions
}

// Social media optimal dimensions
export const SOCIAL_DIMENSIONS = {
  width: 1200,
  height: 630, // 1.9:1 aspect ratio - optimal for Twitter/LinkedIn
}

/**
 * Calculate required canvas height based on content
 */
function calculateHeight(
  lines: ParsedLine[],
  _ctx: CanvasRenderingContext2D,
  fontSize: number,
  lineHeight: number,
  padding: number,
  hasWatermark: boolean,
  hasQrCode: boolean = false
): number {
  const lineCount = lines.length
  const textHeight = lineCount * fontSize * lineHeight
  const headerHeight = 80 // Space for header/title area
  const watermarkHeight = hasWatermark ? 60 : 0
  const qrCodeHeight = hasQrCode ? 40 : 0 // Extra space for QR code

  return Math.max(
    400,
    Math.ceil(padding * 2 + headerHeight + textHeight + watermarkHeight + qrCodeHeight)
  )
}

/**
 * Draw rounded rectangle
 */
function drawRoundedRect(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  width: number,
  height: number,
  radius: number
): void {
  ctx.beginPath()
  ctx.moveTo(x + radius, y)
  ctx.lineTo(x + width - radius, y)
  ctx.quadraticCurveTo(x + width, y, x + width, y + radius)
  ctx.lineTo(x + width, y + height - radius)
  ctx.quadraticCurveTo(x + width, y + height, x + width - radius, y + height)
  ctx.lineTo(x + radius, y + height)
  ctx.quadraticCurveTo(x, y + height, x, y + height - radius)
  ctx.lineTo(x, y + radius)
  ctx.quadraticCurveTo(x, y, x + radius, y)
  ctx.closePath()
}

/**
 * Export terminal content to PNG
 */
export async function exportToPng(
  content: string,
  outputPath: string,
  options: PngExportOptions = {}
): Promise<string> {
  const {
    theme = 'dark',
    watermark = true,
    padding = 40,
    lineHeight = 1.4,
    fontSize = 16,
    qrUrl,
    socialFormat = false,
  } = options

  // Use social media dimensions if requested
  const width = socialFormat ? SOCIAL_DIMENSIONS.width : options.width || 1200

  // Get content configuration (type + styling info)
  const contentConfig = getContentConfig(content)
  const headerInfo = {
    emoji: contentConfig.emoji,
    title: contentConfig.title,
    gradient: contentConfig.gradient,
  }

  // Parse ANSI codes
  const parsedLines = parseAnsiCodes(content, theme)

  // Create temporary canvas for measurements
  const tempCanvas = createCanvas(width, 100)
  const tempCtx = tempCanvas.getContext('2d')
  tempCtx.font = `${fontSize}px "JetBrains Mono", "Fira Code", "SF Mono", Menlo, Monaco, "Courier New", monospace`

  // Calculate height - force social dimensions if requested
  const calculatedHeight = socialFormat
    ? SOCIAL_DIMENSIONS.height
    : options.height ||
      calculateHeight(parsedLines, tempCtx, fontSize, lineHeight, padding, watermark, !!qrUrl)

  // Setup canvas with background gradient
  const ctx = setupCanvas(createCanvas, width, calculatedHeight, theme, headerInfo)

  // Draw decorative elements
  drawDecorations(ctx, width, calculatedHeight, theme, contentConfig.type)

  // Calculate content area
  const contentArea = calculateContentArea(width, calculatedHeight, padding, watermark)

  // Draw terminal-style window
  drawTerminalBox(ctx, contentArea, theme, drawRoundedRect)

  // Draw window header with controls
  drawTerminalHeader(ctx, width, contentArea, theme, headerInfo, drawRoundedRect)

  // Draw text content
  drawTextContent(ctx, contentArea, fontSize, lineHeight, parsedLines)

  // Draw watermark
  if (watermark) {
    drawWatermark(ctx, width, calculatedHeight, theme, !!qrUrl)
  }

  // Draw QR code if URL provided
  if (qrUrl) {
    await drawQrCode(ctx, width, calculatedHeight, padding, qrUrl, theme, drawRoundedRect)
  }

  // Save to file
  const absolutePath = path.resolve(outputPath)
  const canvas = ctx.canvas || tempCanvas
  const buffer = canvas.toBuffer('image/png')
  fs.writeFileSync(absolutePath, buffer)

  return absolutePath
}

/**
 * Draw decorative background elements
 */
function drawDecorations(
  ctx: CanvasRenderingContext2D,
  width: number,
  height: number,
  theme: 'dark' | 'light',
  contentType: string
): void {
  const alpha = theme === 'dark' ? 0.1 : 0.05

  // Draw subtle grid pattern
  ctx.strokeStyle =
    theme === 'dark' ? `rgba(255, 255, 255, ${alpha * 0.3})` : `rgba(0, 0, 0, ${alpha * 0.3})`
  ctx.lineWidth = 1

  // Vertical lines
  for (let x = 0; x < width; x += 40) {
    ctx.beginPath()
    ctx.moveTo(x, 0)
    ctx.lineTo(x, height)
    ctx.stroke()
  }

  // Horizontal lines
  for (let y = 0; y < height; y += 40) {
    ctx.beginPath()
    ctx.moveTo(0, y)
    ctx.lineTo(width, y)
    ctx.stroke()
  }

  // Draw accent circles based on content type
  const circleColor =
    contentType === 'wrapped'
      ? '#6b5ce7'
      : contentType === 'achievements'
        ? '#f9ca24'
        : contentType === 'dna'
          ? '#00d2d3'
          : '#6b5ce7'

  // Top-right decorative circle
  ctx.beginPath()
  ctx.arc(width - 80, 80, 120, 0, Math.PI * 2)
  ctx.fillStyle = `${circleColor}${Math.floor(alpha * 255)
    .toString(16)
    .padStart(2, '0')}`
  ctx.fill()

  // Bottom-left decorative circle
  ctx.beginPath()
  ctx.arc(80, height - 80, 100, 0, Math.PI * 2)
  ctx.fillStyle = `${circleColor}${Math.floor(alpha * 0.5 * 255)
    .toString(16)
    .padStart(2, '0')}`
  ctx.fill()
}

/**
 * Format achievements data for PNG export
 * Returns a plain text representation suitable for rendering
 */
export function formatAchievementsForExport(
  unlocked: Array<{ name: string; emoji: string; description: string }>,
  locked: Array<{ name: string; emoji: string; description: string }>,
  total: number
): string {
  const lines: string[] = []
  const W = 45

  lines.push('')
  lines.push('  \u{1F3C6} ACHIEVEMENTS')
  lines.push('')
  lines.push(`\u250c${'\u2500'.repeat(W)}\u2510`)
  lines.push(`\u2502${' UNLOCKED'.padEnd(W)}\u2502`)
  lines.push(`\u251c${'\u2500'.repeat(W)}\u2524`)

  if (unlocked.length === 0) {
    lines.push(`\u2502${' No achievements unlocked yet...'.padEnd(W)}\u2502`)
  } else {
    for (const achievement of unlocked) {
      const line = ` ${achievement.emoji} ${achievement.name} - ${achievement.description}`
      const truncated = line.slice(0, W)
      lines.push(`\u2502${truncated.padEnd(W)}\u2502`)
    }
  }
  lines.push(`\u2514${'\u2500'.repeat(W)}\u2518`)

  lines.push('')
  lines.push(`\u250c${'\u2500'.repeat(W)}\u2510`)
  lines.push(`\u2502${' \u{1F512} LOCKED'.padEnd(W)}\u2502`)
  lines.push(`\u251c${'\u2500'.repeat(W)}\u2524`)

  if (locked.length === 0) {
    lines.push(`\u2502${' All achievements unlocked!'.padEnd(W)}\u2502`)
  } else {
    for (const achievement of locked) {
      const line = ` ${achievement.emoji} ${achievement.name} - ${achievement.description}`
      const truncated = line.slice(0, W)
      lines.push(`\u2502${truncated.padEnd(W)}\u2502`)
    }
  }
  lines.push(`\u2514${'\u2500'.repeat(W)}\u2518`)

  // Progress
  lines.push('')
  const percent = Math.round((unlocked.length / total) * 100)
  lines.push(`  Progress: ${unlocked.length}/${total} achievements (${percent}%)`)

  // Progress bar
  const barWidth = 30
  const filled = Math.round((unlocked.length / total) * barWidth)
  const empty = barWidth - filled
  const bar = '\u2588'.repeat(filled) + '\u2591'.repeat(empty)
  lines.push(`  ${bar}`)
  lines.push('')

  return lines.join('\n')
}

/**
 * Check if canvas package is available
 */
export async function isPngExportAvailable(): Promise<boolean> {
  try {
    await import('canvas')
    return true
  } catch {
    return false
  }
}

/**
 * Get GitHub repository URL from git remote
 * Returns a clean HTTPS URL suitable for QR codes
 */
export async function getRepoUrl(rootDir: string = '.'): Promise<string | null> {
  try {
    const git: SimpleGit = simpleGit(rootDir)
    const remotes = await git.getRemotes(true)
    const origin = remotes.find((r) => r.name === 'origin')
    const remote = origin?.refs?.fetch || ''

    if (!remote) {
      return null
    }

    // Convert SSH URL to HTTPS
    // git@github.com:user/repo.git -> https://github.com/user/repo
    if (remote.startsWith('git@')) {
      const match = remote.match(/git@([^:]+):(.+?)(\.git)?$/)
      if (match) {
        return `https://${match[1]}/${match[2]}`
      }
    }

    // Already HTTPS, clean up .git suffix
    if (remote.startsWith('https://')) {
      return remote.replace(/\.git$/, '')
    }

    return remote
  } catch {
    return null
  }
}

/**
 * Social Share URL Options
 */
export interface ShareUrls {
  twitter: string
  linkedin: string
  raw: string
}

/**
 * Generate social share URLs for PNG exports
 * Returns pre-filled share links for Twitter and LinkedIn
 */
export function generateShareUrls(
  commandType: string,
  repoUrl?: string | null,
  stats?: { healthScore?: number; complexity?: number }
): ShareUrls {
  const projectName = repoUrl ? repoUrl.split('/').pop() || 'my codebase' : 'my codebase'

  // Craft compelling share text based on command type
  const shareTexts: Record<string, string> = {
    health: `\u{1F47B} Just ran specter health on ${projectName}${stats?.healthScore ? ` - scored ${Math.round(stats.healthScore)}/100!` : ''}\n\nGive your codebase a voice: github.com/specter-cli/specter`,
    roast: `\u{1F525} Got absolutely roasted by Specter...\n\nMy codebase called me out and I deserved it \u{1F62D}\n\nTry it: github.com/specter-cli/specter`,
    wrapped: `\u{1F389} My codebase wrapped is here!\n\nSpotify Wrapped but for code - see your year in commits, complexity trends, and more.\n\nTry Specter: github.com/specter-cli/specter`,
    achievements: `\u{1F3C6} Just unlocked new achievements in my codebase!\n\nGameified code quality with Specter\n\nCheck it out: github.com/specter-cli/specter`,
    dna: `\u{1F9EC} My codebase's DNA visualization is wild!\n\nEvery repo has a unique fingerprint.\n\nGenerate yours: github.com/specter-cli/specter`,
    tinder: `\u{1F525} Would you swipe right on my codebase?\n\nSpecter gave me a Tinder profile for my code lol\n\nTry it: github.com/specter-cli/specter`,
    cost: `\u{1F4B0} Just calculated my tech debt in dollars...\n\n${stats?.complexity ? `$${(stats.complexity * 150).toLocaleString()} estimated remediation cost.` : 'The results were... concerning.'}\n\nTry Specter: github.com/specter-cli/specter`,
    default: `\u{1F47B} Just discovered Specter - gives your codebase a voice!\n\n11 personality modes, DORA metrics, roasts, and more.\n\nCheck it out: github.com/specter-cli/specter`,
  }

  const defaultText = `\u{1F47B} Just discovered Specter - gives your codebase a voice!\n\n11 personality modes, DORA metrics, roasts, and more.\n\nCheck it out: github.com/specter-cli/specter`
  const text = shareTexts[commandType] ?? defaultText
  const encodedText = encodeURIComponent(text)

  return {
    twitter: `https://twitter.com/intent/tweet?text=${encodedText}`,
    linkedin: `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(repoUrl || 'https://github.com/specter-cli/specter')}&summary=${encodedText}`,
    raw: text,
  }
}
